language: python
dist: xenial
sudo: true
os: linux

env:
  global:
    - TWINE_USERNAME=astroduff
    - secure: "hAv1a07lo6B/T/z3+kt4iwvBb3GgT9kUPiKFgjCaVo/qpDWCSsddhwEClr+YwlqhSoGOyP6iEcbmE7HpZ5BKwgoBKdDkPxFZOP6DH7ZGEW4xTrEItSfhgOIyV0sOThTnA5EUv1xh9UQ1GD7WOf1ZYIl2zxadgj+cD0BmEkOfOhr7/c393rUPplfwc20ZJpyesmlxBnAZRIAd9T61uIQKsRN3w0e47G+OWKM8ykwkqsHGQCJV+3C1wHnmtoQyoCpFVq3tlJCQ/cA8UGyljap8cd3+Qp3CoXl9LngvKJS9ojA3cUj1+gZxAz5Jk3jkZlJoqIFM/mu0i/wHXgwKUsd9YJ0huqvnKusS5HAv8a12kYE+L/3oLNbMOrdtSdS1/LmugfLiSdeDMjsas8IRckP3qNPXDPfC5+7CGr2lA3ZxlJeGb4HjWHtbTZLLeGVGB8YuaTZEao+2RuYqR1FYQlIQsEtU8AQ5dQ0EPVPk2e+7N5nabt6InksWBLGu9jZPZCIauKvGgqeC77wZOymKPCawE6lgnwp8ItYL9jC2BtckaFRdVEl/1yySn7wmMnIaQHQRAEmsxe2DcPjnHN2wjbss7OcT8NegTGQTwajQ1lt7yjFqSLlNsZBgK894bK8SrZrYcIIg9WVBWqPuP9NGOGGlLIk6ujuvFfGy2eRqvvi7FPs="
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/

jobs:
  include:
    - os: osx
      python: 2
      language: generic
    - os: osx
      python: 3
      language: generic
      env: PY=3
    - python: 2.7
    - python: 3.5
    - python: 3.5-dev
    - python: 3.6
    - python: 3.6-dev
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
  allow_failures:
    - python: 3.8-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -q
      sudo apt-get install -y swig
    else
      brew update
      brew cleanup
      brew install swig
    fi
  - python$PY -m pip install --upgrade pip setuptools wheel twine

install:
  - python$PY setup.py build_ext --inplace
  - python$PY setup.py sdist bdist_wheel
  - twine check dist/*

script:
  - echo "Hello world"

after_success:
  - python$PY -m pip install auditwheel
  - auditwheel repair dist/*.whl
  - twine upload dist/* --skip-existing

notifications:
  email:
    recipients:
      - mail@alanrduffy.com
    on_success: change
    on_failure: always
    