os: linux
dist: xenial
sudo: true
language: python

env:
  global:
    - TWINE_USERNAME=1313e
    - secure: "MDTcgtmECiD4rZIyDukZV2bT8Vtp/L4lfRGexvDC+hXl9V3U+8lbiginSI8becj+KkZVfYfkyfKIwJuNpcAbtB0D+B4T8l+gz05AonthNhjKfYi2gkxjJQe9KUtCcAS8jvoOuftLXfNnK2KS/fDewgQmEUouaz6ARwU4+juHVyzWyIa57HnJmcqFaGlK1JU11L3vEDkrFgLji9sZ+FjeqNkJ04ozqQhAt9SbxM5ZOCWvj34qfnmKlGl9EQNSvsktM37tNtPRGYycA6kukfsCbPtrKDnqN4xk42AH98MQHgE09BRi5bKvzzOSUk+/0ZsHvWWdzDQUF2gI0ot7wOwxU5Ox3IEzXoLzayMN7gUCYYQDF1iis4dvQrT9POGjXfD9NOX/i+1KSZcmaxHxg30WRqJfwzr08d4jd56zW4nWzjNgTJ84/kFNODWp72qXe1HngjflkDMs8waFe+Qrcq0P+oi4ale6BQORuoHTP+q8jTD+LGQyYqcW+XmLXSby+YQ1HdAZ0wyUlZr2Yx1P/N+toG2juXmiMzf1+Po4U+Ea3eOGGBC2Cqb6de3Z83+yDU183kRPXToYGHhsphLDTU8Y28ik3UpFa77mzNLTElJ0go1k1rdlbPnjT6/Z2x+iJZibkX+G2cBaOyPqOeOKmOpMXOhcQNBQYazfmWc9/imGNXA="
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.15
    - os: osx
      language: generic
      env: PYTHON=3.5.4 PY=3
    - os: osx
      language: generic
      env: PYTHON=3.6.5 PY=3
    - os: osx
      language: generic
      env: PYTHON=3.7.5 PY=3
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull $DOCKER_IMAGE
    else
      brew update
      brew cleanup
      brew uninstall --ignore-dependencies python
      brew install python@$PYTHON
      brew install swig
      python$PY -m pip install --upgrade pip setuptools wheel
      pip$PY install -r requirements.txt
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
    else
      python$PY setup.py sdist -d wheelhouse
      pip$PY wheel . -w wheelhouse
      cd wheelhouse
      pip$PY install cosmolopy --no-index -f .
      python$PY -c "import cosmolopy; import cosmolopy.EH.power"
      cd ..
    fi
  - ls wheelhouse/

after_success:
  - pip$PY install twine
  - twine upload --skip-existing wheelhouse/cosmolopy*

