language: python
dist: xenial
sudo: true
os: linux

env:
  global:
    - TWINE_USERNAME=astroduff
    - secure: "MTukdzgVnPQnwbxlBaeGhwyGH+aa1FU504uilrWa4D79f18Xek5WEofLWgcMPy5HcyQ5wu1mgq6AxsBB4GBsdS5Mcoy1OZDwog08t+YjfmX2YzjO2FCD5Jv7rROYdrF8TswMGg0C9iB9SRRH0wveCY5BrITLUpbDBMkD78OsVTppSlP63/IjYZu958QSmwb6vYPDu23Is5ylez+C0lSn5Ho9cWNlreLKLrgiTsDcH4bUfqcTDtd5gGhv6/x9CMU9bA7IreNO4KL7rhThQlWnM4AteABvdpKe1JyyjGWGyVVUSeR3iGb5e0Fg/sPtNZIfPzSMCNAMFI0yaiF0eIsV2KylAap4uZKUVEsg1l9Sg/BjBbkD26Vn47Ttwm+R0yDFUjEqvYif9btuKOU3a9y7HdLt+inS1bRPn+Qw4U6oQhegoojXRUQf5+dKvYXQuHsXuRvepOggE5jw55gHtfWf3mNl4fK+g2+CLM+O8LCXNCy1rfl2JIuumtKbo+qfDoistOqIEwBZDHWUIQH7G/JaBNtUoG5ckcXTD0hNBf/681VRcfMz3bo+9Pd+j7vZMZk3ZP4rLa6JHI172yvvfn7OgmZzmhvM1VSk5zoqd3Ho47AYVi91M6sEgoXiHwBS890CyeO70r1NZsVv1xY8SysYMfBPN3IeXPWVqbN5gW5W6ME="
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/

jobs:
  include:
    - os: osx
      python: 2
      language: generic
    - os: osx
      python: 3
      language: generic
      env: PY=3
    - python: 2.7
    - python: 3.5
    - python: 3.5-dev
    - python: 3.6
    - python: 3.6-dev
    - python: 3.7
    - python: 3.7-dev
    - python: 3.8-dev
  allow_failures:
    - python: 3.8-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -q
      sudo apt-get install -y swig
    else
      brew update
      brew cleanup
      brew install swig
    fi
  - python$PY -m pip install --upgrade pip setuptools wheel twine

install:
  - python$PY setup.py build_ext --inplace
  - python$PY setup.py sdist bdist_wheel
  - twine check dist/*

script:
  - echo "Hello world"

after_success:
  - python$PY -m pip install auditwheel
  - auditwheel repair dist/*.whl
  - twine upload dist/*

notifications:
  email:
    recipients:
      - mail@alanrduffy.com
    on_success: change
    on_failure: always
    